{application,ggg,
             [{description,[]},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib,jiffy,ssl,cowboy]},
              {mod,{ggg_app,[]}},
              {env,[]},
              {modules,[connect,constants,draw,ggg_app,ggg_sup,
                        internal_handler,main_handler,serve]}]}.
